

CREATE DATABASE WorkWave
GO

USE WorkWave
GO



CREATE TABLE Users (
	UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
	Email NVARCHAR(256) UNIQUE NOT NULL,
	PasswordHash NVARCHAR(50) NOT NULL,
	UserName NVARCHAR(80) UNIQUE NOT NULL,
	ProfileImage VARBINARY(max)
)
GO

CREATE TABLE Projects (
	ProjectId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
	ProjectName NVARCHAR(100) NOT NULL,
	ProjectDescription NVARCHAR(1000) NOT NULL
)
GO

CREATE TABLE Sprints (
	SprintId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
	SprintNumber INT NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL
)
GO

CREATE TABLE WorkItems (
	WorkItemId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
	Title NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	[State] NVARCHAR(50) NOT NULL DEFAULT('New'),
	ProjectId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Projects(ProjectId),
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserId),
	SprintId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Sprints(SprintId)
)
GO

CREATE TABLE PerformanceHistories (
	HistoryId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
	ProjectId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Projects(ProjectId),
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserId),
	[Date] DATETIME DEFAULT(GETDATE()),
	[Description] NVARCHAR(1000) NOT NULL
)
GO

CREATE TABLE Tags (
	TagId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
	TagName NVARCHAR(50) NOT NULL,
	TagColor NVARCHAR(6) NOT NULL,
	WorkItemId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES WorkItems(WorkItemId)
)
GO

CREATE TABLE Comments (
	CommentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
	CommentText NVARCHAR(1000) NOT NULL,
	CommentDate NVARCHAR(6) NOT NULL,
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserId),
	WorkItemId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES WorkItems(WorkItemId)
)
GO

CREATE TABLE Members (
	ProjectId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Projects(ProjectId) DEFAULT(NEWID()),
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserId) DEFAULT(NEWID()),
	PRIMARY KEY (ProjectId, UserId)
)
GO
